import Head from 'next/head'
import { Button, Input, Select } from '../../components/ui-elements';

export default function DesignSystem() {
    const title = 'Weather App | Design System';

    return (
        <div className="outerWrapper">
            <div className="wrapper">
                <Head>
                    <title>{title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="author" content="Effie Pitaouli" />
                    <meta name="keywords" content="weather, google autocomplete, geolocation api" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <h1>Weather App Design System</h1>
                <section>
                    <h2>Color Palette</h2>
                </section>
                <section>
                    <h2>Typography</h2>
                </section>
                <section>
                    <h2>Ui Elements</h2>
                    <Button text="Default button" click={null}></Button>
                    <Input name="default-text" type="text"></Input>
                    <Input name="default-radio" type="radio"></Input>
                    <Select name="default-select"></Select>
                </section>
            </div>
        </div>
    )
}
