import Head from 'next/head'
import { useEffect, useState } from 'react';
import styles from '../../styles/pages/DesignSystem.module.css';
import { Button, Input, Select } from '../../components/ui-elements';
//import ReactHtmlParser from 'react-html-parser';

export default function DesignSystem() {
    const title = 'Weather App | Design System';
    const [variables, setVariables] = useState([]);

    useEffect(() => {
        const values = [];
        const cssVariables = Array.from(document.styleSheets)
            .filter(
                sheet =>
                    sheet.href === null || sheet.href.startsWith(window.location.origin)
            )
            .reduce(
                (acc, sheet) =>
                (acc = [
                    ...acc,
                    ...Array.from(sheet.cssRules).reduce(
                        (def, rule) =>
                        (def =
                            rule.selectorText === ":root"
                                ? [
                                    //...def,
                                    ...Array.from(rule.style).filter(name => {
                                        if (name.startsWith("--color")) {
                                            values.push(rule.style.getPropertyValue(name));
                                            return name;
                                        };
                                    }

                                    )
                                ]
                                : def),
                        []
                    )
                ]),
                []
            );
        console.log(cssVariables);
        console.log(values);
        const css = Array.from(cssVariables).map((e, i) => {
            // console.log(e);
            // console.log(i);
            return [e.slice(7), values[i]];
        });
        console.log(css);
        setVariables(css);
    }, []);

    // function loadCss() {
    //     console.log('in loadCss');
    //     require('../../styles/utils/variables.css').then(

    //     )
    // }

    return (
        <div className="outerWrapper outerWrapper--auto">
            <div className="wrapper wrapper--full">
                <Head>
                    <title>{title}</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="author" content="Effie Pitaouli" />
                    <meta name="keywords" content="weather, google autocomplete, geolocation api" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <h1>Weather App Design System</h1>
                <section className={styles['designSystem__section']}>
                    <h2>Color Palette</h2>
                    {
                        variables.map((e) => {
                            return <div className={`u-flex ${styles['designSystem__row']}`}><span>{e[0]}</span> <span className="u-block" style={{ background: e[1] }}></span></div>
                        })
                    }
                </section>
                <section className={styles['designSystem__section']}>
                    <h2>Typography</h2>
                    {/* https://zhenyong.github.io/react/tips/dangerously-set-inner-html.html */}
                    {[...Array(6)].map((x, i) =>
                        <div key={i} className={styles['designSystem__row']} dangerouslySetInnerHTML={{ __html: `<h${i + 1}>Heading ${i + 1}</h${i + 1}>` }}>
                        </div>
                    )}
                    {/* TO DO
                        Make the below code automatically generated
                    */}
                    <div className={styles['designSystem__row']}><p>Paragraph</p></div>
                    <div className={styles['designSystem__row']}><div className="underline">Underlined</div></div>
                </section>
                <section className={styles['designSystem__section']}>
                    <h2>Ui Elements</h2>
                    <div className={styles['designSystem__row']}>
                        <Button text="Default button" click={() => { }}></Button>
                    </div>
                    <div className={styles['designSystem__row']}>
                        <Input name="default-text" type="text"></Input>
                    </div>

                    {/* <Input name="default-radio" type="radio"></Input>
                    <Select name="default-select"></Select> */}
                </section>
            </div>
        </div>
    )
}
