import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Results } from '../components/results';
import { Location } from '../components/location';
import { Settings } from '../components/settings';
import { useState, useEffect, use } from 'react';
import Cookies from 'universal-cookie';

export default function Home() {
  const cookies = new Cookies();
  const [coords, setCoords] = useState(['', '']);
  const [theme, setTheme] = useState('light');
  const [hasLocation, setHasLocation] = useState(false);

  function userPreferences() {
    if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
      setTheme('dark');
    };
  }

  useEffect(() => {
    userPreferences();
    cookies.get('coordinates') && setCoords(cookies.get('coordinates').split(','));
  }, []);

  useEffect(() => {
    const bodyElement = document.getElementsByTagName('body')[0];
    bodyElement.classList = `theme-${theme}`;
  }, [theme]);

  function changeTheme() {
    setTheme(theme == 'dark' ? 'light' : 'dark');
  }

  function handleLocation(coords: string, location: string) {
    setCoords(coords.split(','));
    setHasLocation(true);
  }

  return (
    <div className="wrapper">
      <Head>
        <title>Effie's Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Effie Pitaouli" />
        <meta name="keywords" content="weather, google autocomplete, geolocation api" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Settings theme={changeTheme} dark={theme}></Settings>
      <Location handlePlace={handleLocation}></Location>
      <Results coordinates={coords} hasLocation={hasLocation}></Results>
    </div>
  )
}
