import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Results } from '../components/results';
import { Location } from '../components/location';
import { Settings } from '../components/settings';
import { useState, useEffect } from 'react';

export default function Home() {
  const [theme, setTheme] = useState('light');

  function userPreferences() {
    if (window.matchMedia('(prefers-color-scheme: dark)').matches) {
      setTheme('dark')
    };
  }

  useEffect(() => {
    userPreferences();
  }, []);

  function changeTheme() {
    setTheme(theme == 'dark' ? 'light' : 'dark');
  }

  return (
    <div className={`theme-${theme}`}>
      <Head>
        <title>Effie's Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="author" content="Effie Pitaouli" />
        <meta name="keywords" content="weather, google autocomplete, geolocation api" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Settings theme={changeTheme} dark={theme}></Settings>
      <Location></Location>
      <Results></Results>
    </div>
  )
}
